export const games = [
  { id:'code-breaker', title:'Code Breaker', thaiTitle:'ถอดรหัสลับ', description:'เกมเดารหัสลับด้วยตรรกะ ใช้จำนวนครั้งให้น้อยที่สุด', longDescription:'เกมแนวตรรกะและการวิเคราะห์ ผู้เล่นต้องเดารหัสลับให้ถูก โดยระบบจะบอกจำนวนตัวเลขที่ถูกตำแหน่งและตัวเลขที่ถูกแต่ผิดตำแหน่ง เหมาะกับธีม sci-fi terminal และการถอดรหัสระบบ', category:'strategy', difficulty:'Medium', status:'available', url:'/games/code-breaker', icon:'⌬', bestScoreKey:'codeBreakerBestScore', tags:['Logic','Code','Strategy','Puzzle','Deduction'] },
  { id:'cipher-typing', title:'Cipher Typing', thaiTitle:'พิมพ์รหัสคำสั่ง', description:'เกมพิมพ์คำสั่งให้เร็วและแม่น ก่อนเวลาหมด', longDescription:'เกมแนว typing และ reflex ที่ผู้เล่นต้องพิมพ์คำสั่งบนหน้าจอให้ถูกต้องและรวดเร็ว เหมาะกับธีม sci-fi terminal ฝึกความเร็ว ความแม่นยำ และสมาธิ', category:'arcade', difficulty:'Medium', status:'available', url:'/games/cipher-typing', icon:'▣', bestScoreKey:'cipherTypingBestScore', tags:['Typing','Speed','Accuracy','Terminal','Arcade'] },
  { id:'connect-four', title:'4 In A Row', thaiTitle:'เรียง 4', description:'เกมเรียง 4 ตัว เล่นกับ Machine พร้อมระดับความยาก', longDescription:'เกมวางแผนที่ผู้เล่นต้องเรียงเหรียญให้ได้ 4 ตัวติดกันก่อน Machine รองรับหลายระดับความยาก ตั้งแต่สุ่มเล่นจนถึง Minimax', category:'strategy', difficulty:'Medium', status:'available', url:'/games/connect-four', icon:'◉', bestScoreKey:'connectFourBestScore', tags:['AI','Machine','Strategy','Minimax'] },
  { id:'xo', title:'XO Battle', thaiTitle:'XO Battle', description:'เกม XO เล่นกับ Machine จบไว ใช้ตรรกะ', longDescription:'เกม XO คลาสสิก 3x3 เล่นกับ Machine มีหลายระดับความยาก เหมาะสำหรับฝึกตรรกะและการวางแผน', category:'classic', difficulty:'Easy', status:'available', url:'/games/xo', icon:'✕○', bestScoreKey:'xoBestScore', tags:['Classic','Logic','Quick'] },
  { id:'memory-card', title:'Memory Card', thaiTitle:'จับคู่การ์ด', description:'เกมจับคู่การ์ด ฝึกความจำและสมาธิ', longDescription:'เกมเปิดการ์ดเพื่อจับคู่ไอคอนที่เหมือนกัน วัดผลจากจำนวนครั้งที่เปิดและเวลาที่ใช้', category:'puzzle', difficulty:'Easy', status:'available', url:'/games/memory-card', icon:'◫', bestScoreKey:'memoryCardBestScore', tags:['Puzzle','Memory','Focus'] },
  { id:'snake', title:'Snake', thaiTitle:'เกมงู', description:'เกมงูคลาสสิก เก็บคะแนนให้สูงที่สุด', longDescription:'เกมงูแนว arcade คลาสสิก ควบคุมทิศทางเพื่อเก็บอาหารและทำคะแนนให้สูงที่สุด', category:'arcade', difficulty:'Medium', status:'available', url:'/games/snake', icon:'⟲', bestScoreKey:'snakeBestScore', tags:['Arcade','Score','Classic'] },
  { id:'reaction-rush', title:'Reaction Rush', thaiTitle:'เกมวัดรีเฟล็กซ์', description:'เกมทดสอบความไว กดให้ทันเมื่อสัญญาณปรากฏ', longDescription:'เกมแนวรีเฟล็กซ์ที่ผู้เล่นต้องรอจังหวะสัญญาณแล้วกดให้เร็วที่สุด เหมาะสำหรับวัดความไว การตอบสนอง และสมาธิ', category:'arcade', difficulty:'Easy', status:'available', url:'/games/reaction-rush', icon:'⏱', bestScoreKey:'reactionRushBestScore', tags:['Reflex','Speed','Focus','Arcade'] },
  { id:'aim-grid', title:'Aim Grid', thaiTitle:'เกมเล็งเป้า', description:'เกมคลิกเป้าหมายให้เร็วและแม่นที่สุดในเวลาจำกัด', longDescription:'เกมแนวรีเฟล็กซ์และความแม่นยำ ผู้เล่นต้องคลิกหรือแตะเป้าหมายที่สุ่มปรากฏบนตารางให้ได้มากที่สุดภายในเวลาที่กำหนด พร้อมวัดคะแนน ความแม่นยำ และคอมโบ', category:'arcade', difficulty:'Medium', status:'available', url:'/games/aim-grid', icon:'◎', bestScoreKey:'aimGridBestScore', tags:['Aim','Reflex','Speed','Accuracy','Arcade'] },
  { id:'grid-runner', title:'Grid Runner', thaiTitle:'นักวิ่งตาราง', description:'เกมเดินในตารางไปถึงเป้าหมายโดยใช้จำนวนก้าวให้น้อยที่สุด', longDescription:'เกมวางแผนเส้นทางบนตาราง ผู้เล่นต้องพาตัวละครจากจุดเริ่มต้นไปยังเป้าหมาย หลบกำแพงและสิ่งกีดขวาง พร้อมเก็บคะแนนจากจำนวนก้าวและเวลาที่ใช้', category:'strategy', difficulty:'Medium', status:'available', url:'/games/grid-runner', icon:'◈', bestScoreKey:'gridRunnerBestScore', tags:['Grid','Pathfinding','Strategy','Puzzle','Maze'] },
  { id:'math-rain', title:'Math Rain', thaiTitle:'ฝนตัวเลข', description:'เกมคิดเลขเร็ว ตอบโจทย์ที่ตกลงมาก่อนจะถึงพื้น', longDescription:'เกมฝึกสมองแนว arcade ที่โจทย์คณิตศาสตร์จะตกลงมาจากด้านบน ผู้เล่นต้องพิมพ์คำตอบให้ถูกก่อนโจทย์ตกถึงพื้น ยิ่งตอบไวและต่อเนื่อง คะแนนยิ่งสูง', category:'puzzle', difficulty:'Medium', status:'available', url:'/games/math-rain', icon:'∑', bestScoreKey:'mathRainBestScore', tags:['Math','Brain','Speed','Puzzle','Arcade'] },
  { id:'laser-maze', title:'Laser Maze', thaiTitle:'เขาวงกตเลเซอร์', description:'เกมวางกระจกสะท้อนลำแสงให้ไปถึงเป้าหมาย', longDescription:'เกม puzzle แนวตรรกะที่ผู้เล่นต้องหมุนหรือวางกระจกในตารางเพื่อสะท้อนลำแสงจากจุดเริ่มต้นให้เดินทางไปถึงเป้าหมาย ใช้การคิดเชิงพื้นที่และการวางแผน', category:'strategy', difficulty:'Hard', status:'available', url:'/games/laser-maze', icon:'◇', bestScoreKey:'laserMazeBestScore', tags:['Laser','Logic','Puzzle','Strategy','Maze'] },
  { id:'number-ninja', title:'Number Ninja', thaiTitle:'นินจาตัวเลข', description:'เกมฝึกสมอง คิดเลขเร็ว ตอบให้ไวและแม่นยำ', longDescription:'เกมพัฒนาสมองที่ให้ผู้เล่นแก้โจทย์ตัวเลขแบบรวดเร็ว ฝึกการคิดเลข สมาธิ และความแม่นยำ', category:'puzzle', difficulty:'Medium', status:'available', url:'/games/number-ninja', icon:'🥷', bestScoreKey:'numberNinjaBestScore', tags:['Brain','Math','Puzzle','Speed'] },
];
