'use client';
import { useEffect, useMemo, useRef, useState } from 'react';
import { getNumberStorage, setNumberStorage } from '@/lib/storage';
import { playLoseSound, playMoveSound, playWinSound } from '@/lib/sound';
import { extendSequence } from '@/lib/memory-sequence/sequence';

const CFG={easy:{size:3,start:2,flash:700,time:null,label:'Easy'},normal:{size:4,start:3,flash:500,time:8,label:'Normal'},hard:{size:5,start:4,flash:320,time:6,label:'Hard'}};

export default function MemorySequenceGame(){const [difficulty,setDifficulty]=useState('normal');const [state,setState]=useState('idle');const [sequence,setSequence]=useState([]);const [activeCell,setActiveCell]=useState(null);const [inputIndex,setInputIndex]=useState(0);const [level,setLevel]=useState(1);const [score,setScore]=useState(0);const [mistakes,setMistakes]=useState(0);const [best,setBest]=useState(0);const [countdown,setCountdown]=useState(null);const timerRef=useRef(null);const flashRef=useRef([]);const cfg=CFG[difficulty];
useEffect(()=>setBest(getNumberStorage('memorySequenceBestScore',0)),[]);
const clear=()=>{if(timerRef.current)clearInterval(timerRef.current);timerRef.current=null;flashRef.current.forEach(clearTimeout);flashRef.current=[];}; useEffect(()=>()=>clear(),[]);
const reset=()=>{clear();setState('idle');setSequence([]);setActiveCell(null);setInputIndex(0);setLevel(1);setScore(0);setMistakes(0);setCountdown(cfg.time);}; useEffect(()=>{reset();},[difficulty]);
const show=(seq)=>{clear();setState('showing');setInputIndex(0);setCountdown(cfg.time);seq.forEach((cell,i)=>{flashRef.current.push(setTimeout(()=>{setActiveCell(cell);playMoveSound();}, i*(cfg.flash+120)));flashRef.current.push(setTimeout(()=>setActiveCell(null), i*(cfg.flash+120)+cfg.flash));});flashRef.current.push(setTimeout(()=>{setState('input');if(cfg.time){let left=cfg.time;setCountdown(left);timerRef.current=setInterval(()=>{left-=1;setCountdown(left);if(left<=0){clearInterval(timerRef.current);timerRef.current=null;setState('failed');setMistakes((m)=>m+1);playLoseSound();}},1000);}}, seq.length*(cfg.flash+120)+150));};
const start=()=>{const cellCount=cfg.size*cfg.size;let seq=[];for(let i=0;i<cfg.start;i++)seq=extendSequence(seq,cellCount);setSequence(seq);show(seq);setNumberStorage('memorySequenceTotalPlays',getNumberStorage('memorySequenceTotalPlays',0)+1);};
const fail=()=>{setState('failed');setMistakes((m)=>m+1);playLoseSound();clear();const old=getNumberStorage('memorySequenceBestScore',0);if(level>old){setNumberStorage('memorySequenceBestScore',level);setNumberStorage('memorySequenceBestLevel',level);playWinSound();setBest(level);} };
const click=(idx)=>{if(state!=='input') return; playMoveSound(); if(sequence[inputIndex]!==idx){fail(); return;} const next=inputIndex+1; setInputIndex(next); if(next===sequence.length){clear(); setState('success'); const nextLevel=level+1; setScore((s)=>s+level*10); setLevel(nextLevel); setNumberStorage('memorySequenceBestStreak',Math.max(getNumberStorage('memorySequenceBestStreak',0),nextLevel-1)); const nextSeq=extendSequence(sequence,cfg.size*cfg.size); setSequence(nextSeq); setTimeout(()=>show(nextSeq),550);} };
const cells=useMemo(()=>Array.from({length:cfg.size*cfg.size},(_,i)=>i),[cfg.size]);
const status={idle:'พร้อมจำลำดับสัญญาณ',showing:'กำลังแสดงสัญญาณ...',input:'กดตามลำดับที่จำได้',success:'ถูกต้อง',failed:countdown===0?'สัญญาณขาดหาย':'ผิดลำดับ!'}[state];
return <div className='space-y-4'><div className='grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-3 font-hud'>{[['เลเวล',level],['คะแนน',score],['เลเวลสูงสุด',best?`เลเวล ${best}`:'-'],['ความยาวลำดับ',sequence.length],['ผิดพลาด',mistakes],['เวลา',cfg.time?`${countdown ?? cfg.time}s`:'∞']].map(([k,v])=><div key={k} className='metal-card p-3'><p className='text-xs text-zinc-400'>{k}</p><p className='text-lg font-bold'>{v}</p></div>)}</div><div className='metal-card p-4 space-y-3'><div className='flex flex-wrap gap-2'>{Object.entries(CFG).map(([k,v])=><button key={k} onClick={()=>setDifficulty(k)} className={`px-3 py-2 border rounded-lg font-hud text-xs ${difficulty===k?'bg-white text-black border-white':'border-white/20'}`}>{v.label}</button>)}<button onClick={start} className='px-4 py-2 rounded-lg bg-white text-black font-hud text-xs font-bold'>เริ่ม</button><button onClick={reset} className='px-4 py-2 rounded-lg border border-white/20 font-hud text-xs'>เริ่มใหม่</button></div><p className='text-sm text-zinc-300'>{status}</p><div className='rounded-2xl border border-white/15 p-3 bg-black/30'><div className='grid gap-2 max-w-[720px] mx-auto' style={{gridTemplateColumns:`repeat(${cfg.size}, minmax(0,1fr))`}}>{cells.map((i)=>{const active=activeCell===i;return <button key={i} onClick={()=>click(i)} className={`aspect-square rounded-md border transition ${active?'border-white bg-white/50 shadow-[0_0_20px_rgba(255,255,255,.35)]':'border-white/10 bg-white/[0.04]'} ${state!=='input'?'pointer-events-none':''}`} />;})}</div></div></div></div>; }
