'use client';
import { useEffect, useMemo, useRef, useState } from 'react';
import { getNumberStorage, setNumberStorage } from '@/lib/storage';
import { playMoveSound, playWinSound } from '@/lib/sound';
import { checkCircuitConnected, rotateConnectionsClockwise } from '@/lib/circuit-link/circuit';
import { cloneCircuitGrid, generateCircuitPuzzle } from '@/lib/circuit-link/generator';

const DIFF=['easy','normal','hard']; const sym=(cell)=>{if(cell.type==='source')return '◉';if(cell.type==='core')return '◎';if(cell.type==='block')return '■';if(cell.type==='empty')return '';const c=cell.connections.join(',');const m={'up,down':'│','left,right':'─','up,right':'└','right,down':'┌','down,left':'┐','left,up':'┘'};return m[c]||'·';};

export default function CircuitLinkGame(){const [difficulty,setDifficulty]=useState('normal');const [puzzle,setPuzzle]=useState(null);const [grid,setGrid]=useState([]);const [state,setState]=useState('playing');const [rotationCount,setRotationCount]=useState(0);const [elapsed,setElapsed]=useState(0);const [best,setBest]=useState(null);const [powered,setPowered]=useState(new Set());const timer=useRef(null);
const load=(d=difficulty)=>{const p=generateCircuitPuzzle(d);setPuzzle(p);setGrid(cloneCircuitGrid(p.grid));setState('playing');setRotationCount(0);setElapsed(0);const bs=getNumberStorage('circuitLinkBestScore',null);if(bs!==null)setBest({text:bs,rot:getNumberStorage('circuitLinkBestRotations',0),time:getNumberStorage('circuitLinkBestTime',0)});};
useEffect(()=>{load(difficulty);},[difficulty]);useEffect(()=>()=>{if(timer.current)clearInterval(timer.current);},[]);
useEffect(()=>{if(timer.current)clearInterval(timer.current); if(state==='playing') timer.current=setInterval(()=>setElapsed((v)=>v+1),1000); return ()=>{if(timer.current)clearInterval(timer.current);};},[state,puzzle?.id]);
useEffect(()=>{if(!grid.length) return; const res=checkCircuitConnected(grid); setPowered(new Set(res.poweredCells.map((p)=>`${p.row},${p.col}`))); if(res.connected && state==='playing'){setState('completed'); const oldRot=getNumberStorage('circuitLinkBestRotations',999999); const oldTime=getNumberStorage('circuitLinkBestTime',999999); if(rotationCount<oldRot||(rotationCount===oldRot&&elapsed<oldTime)){setNumberStorage('circuitLinkBestRotations',rotationCount);setNumberStorage('circuitLinkBestTime',elapsed);const text=`หมุน ${rotationCount} ครั้ง / ${elapsed} วินาที`;setNumberStorage('circuitLinkBestScore',text);setBest({text,rot:rotationCount,time:elapsed});playWinSound();}}},[grid,state,rotationCount,elapsed]);
const rotate=(r,c)=>{if(state!=='playing')return; const cell=grid[r][c]; if(!cell?.rotatable) return; playMoveSound(); setGrid((g)=>{const n=cloneCircuitGrid(g); n[r][c].connections=rotateConnectionsClockwise(n[r][c].connections); return n;}); setRotationCount((v)=>v+1);};
const restart=()=>{if(!puzzle)return;setGrid(cloneCircuitGrid(puzzle.grid));setState('playing');setRotationCount(0);setElapsed(0);};
const size=puzzle?.size||0;
return <div className='space-y-4'><div className='grid grid-cols-2 md:grid-cols-5 gap-3 font-hud'>{[['จำนวนครั้งที่หมุน',rotationCount],['เวลา',`${elapsed}s`],['สถานะ',state==='completed'?'Core online':'ยังเชื่อมต่อไม่สำเร็จ'],['Best',best?.text||'-'],['โหมด',difficulty]].map(([k,v])=><div key={k} className='metal-card p-3'><p className='text-xs text-zinc-400'>{k}</p><p className='text-sm md:text-base font-bold'>{v}</p></div>)}</div><div className='metal-card p-4 space-y-3'><div className='flex flex-wrap gap-2'>{DIFF.map((d)=><button key={d} onClick={()=>setDifficulty(d)} className={`px-3 py-2 rounded-lg border font-hud text-xs ${difficulty===d?'bg-white text-black border-white':'border-white/20'}`}>{d}</button>)}<button onClick={restart} className='px-4 py-2 rounded-lg border border-white/20 font-hud text-xs'>เริ่มใหม่</button><button onClick={()=>load(difficulty)} className='px-4 py-2 rounded-lg bg-white text-black font-hud text-xs font-bold'>สร้างแผงวงจรใหม่</button></div><p className='text-sm text-zinc-300'>หมุนชิ้นส่วนวงจรเพื่อส่งพลังงานไปยัง Core</p><div className='rounded-2xl border border-white/15 p-2 bg-black/30'><div className='grid gap-1 mx-auto' style={{gridTemplateColumns:`repeat(${size}, minmax(0,1fr))`,maxWidth:'760px'}}>{grid.flatMap((row,r)=>row.map((cell,c)=>{const on=powered.has(`${r},${c}`); return <button key={`${r}-${c}`} onClick={()=>rotate(r,c)} className={`aspect-square rounded border font-hud text-lg md:text-xl transition ${on?'border-white bg-white/20 shadow-[0_0_14px_rgba(255,255,255,.3)]':'border-white/10 bg-white/[0.03]'} ${cell.type==='block'?'text-zinc-600':cell.type==='core'?'text-emerald-200':cell.type==='source'?'text-white':'text-zinc-200'}`}>{sym(cell)}</button>; }))}</div></div>{state==='completed'&&<p className='font-hud text-emerald-200'>เชื่อมต่อสำเร็จ! Core online</p>}</div></div>; }
