'use client';
import { useEffect, useMemo, useRef, useState } from 'react';
import { getNumberStorage, setNumberStorage } from '@/lib/storage';
import { playLoseSound, playMoveSound, playWinSound } from '@/lib/sound';
const DURATION=30; const BEST='aimGridBestScore';
const DIFF={easy:{size:5,relocateMs:null,target:'h-8 w-8 md:h-10 md:w-10'},normal:{size:6,relocateMs:1800,target:'h-7 w-7 md:h-8 md:w-8'},hard:{size:7,relocateMs:1200,target:'h-6 w-6 md:h-7 md:w-7'}};
const next=(size,prev)=>{const t=size*size;let n=Math.floor(Math.random()*t);if(prev!==null&&t>1&&n===prev)n=(n+1+Math.floor(Math.random()*(t-1)))%t;return n;};
export default function AimGridGame(){const [difficulty,setDifficulty]=useState('normal');const [state,setState]=useState('idle');const [timeLeft,setTimeLeft]=useState(DURATION);const [targetCell,setTargetCell]=useState(null);const [score,setScore]=useState(0);const [hits,setHits]=useState(0);const [misses,setMisses]=useState(0);const [combo,setCombo]=useState(0);const [best,setBest]=useState(null);const [newBest,setNewBest]=useState(false);const [flash,setFlash]=useState(false);const cfg=DIFF[difficulty];const tRef=useRef(null),rRef=useRef(null),fRef=useRef(null),sRef=useRef(0),hRef=useRef(0),mRef=useRef(0);useEffect(()=>{sRef.current=score;hRef.current=hits;mRef.current=misses;},[score,hits,misses]);useEffect(()=>setBest(getNumberStorage(BEST,null)),[]);
const clearAll=()=>{if(tRef.current)clearInterval(tRef.current);if(rRef.current)clearInterval(rRef.current);if(fRef.current)clearTimeout(fRef.current);tRef.current=null;rRef.current=null;fRef.current=null;};
const reset=()=>{clearAll();setState('idle');setTimeLeft(DURATION);setTargetCell(null);setScore(0);setHits(0);setMisses(0);setCombo(0);setNewBest(false);setFlash(false);};
useEffect(()=>()=>clearAll(),[]);useEffect(()=>{reset();},[difficulty]);
const finish=(fs,fh,fm)=>{clearAll();setState('finished');playLoseSound();setNumberStorage('aimGridTotalPlays',getNumberStorage('aimGridTotalPlays',0)+1);const acc=fh+fm?Number(((fh/(fh+fm))*100).toFixed(2)):0;setNumberStorage('aimGridBestAccuracy',Math.max(getNumberStorage('aimGridBestAccuracy',0),acc));const old=getNumberStorage(BEST,null);if(old===null||fs>old){setNumberStorage(BEST,fs);setBest(fs);setNewBest(true);playWinSound();}};
const move=()=>setTargetCell((p)=>next(cfg.size,p));
const start=()=>{clearAll();setState('playing');setTimeLeft(DURATION);setScore(0);setHits(0);setMisses(0);setCombo(0);setNewBest(false);setTargetCell(next(cfg.size,null));tRef.current=setInterval(()=>setTimeLeft((v)=>{if(v<=1){finish(sRef.current,hRef.current,mRef.current);return 0;}return v-1;}),1000);if(cfg.relocateMs)rRef.current=setInterval(move,cfg.relocateMs);};
const click=(i)=>{if(state!=='playing'||targetCell===null)return;if(i===targetCell){playMoveSound();setHits((v)=>v+1);setCombo((v)=>v+1);setScore((v)=>v+1);move();return;}setMisses((v)=>v+1);setCombo(0);if(difficulty==='hard')setScore((v)=>Math.max(0,v-1));setFlash(true);playLoseSound();fRef.current=setTimeout(()=>setFlash(false),170);};
const acc=hits+misses?(hits/(hits+misses))*100:0;const cells=useMemo(()=>Array.from({length:cfg.size*cfg.size},(_,i)=>i),[cfg.size]);
return <div className='space-y-4'><div className='grid grid-cols-2 md:grid-cols-4 lg:grid-cols-7 gap-3'>{[['เวลา',`${timeLeft}s`],['คะแนน',score],['Best',best??'-'],['Hit',hits],['Miss',misses],['Accuracy',`${acc.toFixed(1)}%`],['Combo',combo]].map(([k,v])=><div key={k} className='metal-card p-3'><p className='font-hud text-xs text-zinc-400'>{k}</p><p className='font-hud text-xl font-bold'>{v}</p></div>)}</div><div className='metal-card p-4 md:p-6 space-y-4'><div className='flex flex-wrap gap-2 items-center'>{Object.keys(DIFF).map((k)=><button key={k} onClick={()=>setDifficulty(k)} className={`px-3 py-2 rounded-lg border font-hud text-xs ${difficulty===k?'bg-white text-black border-white':'border-white/20'}`}>{k}</button>)}<button onClick={start} className='px-4 py-2 rounded-lg bg-white text-black font-hud text-xs font-bold'>{state==='playing'?'เล่นอยู่':'เริ่มเกม'}</button><button onClick={reset} className='px-4 py-2 rounded-lg border border-white/20 font-hud text-xs'>รีสตาร์ต</button></div><p className='text-sm text-zinc-400'>{state==='idle'?'พร้อมเริ่มเกม':state==='playing'?'เล็งเป้าแล้วคลิกให้เร็วที่สุด':newBest?'หมดเวลา! คะแนนใหม่ดีที่สุด!':'หมดเวลา!'}</p><div className={`rounded-2xl border p-2 md:p-3 transition ${flash?'border-rose-400/60 bg-rose-500/10':'border-white/15 bg-black/20'}`}><div className='grid gap-1.5 aspect-square w-full max-w-[680px] mx-auto' style={{gridTemplateColumns:`repeat(${cfg.size}, minmax(0, 1fr))`}}>{cells.map((i)=><button key={i} onClick={()=>click(i)} className='relative rounded-md border border-white/10 bg-white/[0.03] hover:bg-white/[0.06] active:scale-[0.98] transition'>{state==='playing'&&i===targetCell&&<span className={`absolute inset-0 m-auto ${cfg.target} rounded-full border border-white/80 shadow-[0_0_16px_rgba(255,255,255,.35)]`}><span className='absolute inset-1 rounded-full border border-white/70'/><span className='absolute left-1/2 top-0 h-full w-px -translate-x-1/2 bg-white/60'/><span className='absolute top-1/2 left-0 h-px w-full -translate-y-1/2 bg-white/60'/></span>}</button>)}</div></div></div></div>;}
