import type { ChangeEvent } from 'react';
import { useAppStore } from '../store/useAppStore';

export const HomePage = () => { const history=useAppStore(s=>s.history.slice(0,5)); return <div><h2 className='text-2xl font-bold'>Welcome 🎉</h2><p>Play locally, track scores, and have fun.</p><div className='mt-4 space-y-2'>{history.map(h=><div key={h.id} className='card'>{h.game}: {h.result}</div>)}</div></div>; };
export const GamesPage = () => { const setPage=useAppStore(s=>s.setPage); return <div className='grid md:grid-cols-3 gap-4'>{[['tic-tac-toe','Tic Tac Toe'],['memory-card','Memory Card'],['number-puzzle','Number Puzzle']].map(([k,l])=><button key={k} className='card text-left' onClick={()=>setPage(k as any)}>{l}</button>)}</div>; };
export const PlayersPage = () => { const players=useAppStore(s=>s.players); const add=useAppStore(s=>s.addPlayer); const del=useAppStore(s=>s.removePlayer); return <div><button className='btn mb-3' onClick={()=>{const n=prompt('Player name'); if(n) add(n);}}>Add Player</button>{players.map(p=><div key={p.id} className='card flex justify-between'>{p.name}<button onClick={()=>del(p.id)}>Remove</button></div>)}</div>; };
export const LeaderboardPage = () => { const items=useAppStore(s=>s.leaderboard); return <div className='space-y-2'>{items.map(i=><div key={i.id} className='card'>{i.game} - {i.playerName}: {i.scoreLabel}</div>)}</div>; };
export const SettingsPage = () => { const theme=useAppStore(s=>s.theme); const setTheme=useAppStore(s=>s.setTheme); const reset=useAppStore(s=>s.resetAll); const state=useAppStore(s=>({players:s.players,leaderboard:s.leaderboard,history:s.history,theme:s.theme})); const importData=useAppStore(s=>s.importData);
 const exp=()=>{const b=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}); const a=document.createElement('a'); a.href=URL.createObjectURL(b); a.download='local-game-hub.json'; a.click();};
 const imp=(e:ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0]; if(!f) return; f.text().then(t=>importData(JSON.parse(t)));};
 return <div className='space-y-3'><button className='btn' onClick={()=>setTheme(theme==='light'?'dark':'light')}>Theme: {theme}</button><button className='btn' onClick={exp}>Export Data</button><label className='btn inline-block'>Import Data<input type='file' accept='application/json' onChange={imp} className='hidden'/></label><button className='btn bg-red-500 text-white' onClick={reset}>Reset All</button></div>; };
