'use client';
import { useEffect, useMemo, useRef, useState } from 'react';
import { getNumberStorage, getStringStorage, setNumberStorage, setStringStorage } from '@/lib/storage';
import { playMoveSound, playWinSound } from '@/lib/sound';
const CFG={easy:{size:7,density:0.18},normal:{size:9,density:0.24},hard:{size:11,density:0.3}};const START={r:0,c:0};const DIR={up:[-1,0],down:[1,0],left:[0,-1],right:[0,1]};
const bfs=(walls,size,start,goal)=>{const q=[start],seen=new Set([`${start.r},${start.c}`]);while(q.length){const cur=q.shift();if(cur.r===goal.r&&cur.c===goal.c)return true;Object.values(DIR).forEach(([dr,dc])=>{const nr=cur.r+dr,nc=cur.c+dc,k=`${nr},${nc}`;if(nr>=0&&nc>=0&&nr<size&&nc<size&&!walls.has(k)&&!seen.has(k)){seen.add(k);q.push({r:nr,c:nc});}});}return false;};
export default function GridRunnerGame(){const [difficulty,setDifficulty]=useState('normal');const [state,setState]=useState('idle');const [player,setPlayer]=useState(START);const [steps,setSteps]=useState(0);const [time,setTime]=useState(0);const [walls,setWalls]=useState(new Set());const [trail,setTrail]=useState(new Set(['0,0']));const [bestScore,setBestScore]=useState('-');const [bestSteps,setBestSteps]=useState(null);const [bestTime,setBestTime]=useState(null);const timerRef=useRef(null);const size=CFG[difficulty].size;const goal=useMemo(()=>({r:size-1,c:size-1}),[size]);
const clearTimer=()=>{if(timerRef.current)clearInterval(timerRef.current);timerRef.current=null;};useEffect(()=>()=>clearTimer(),[]);
const gen=()=>{for(let t=0;t<40;t+=1){const w=new Set();for(let r=0;r<size;r+=1)for(let c=0;c<size;c+=1){if((r===0&&c===0)||(r===goal.r&&c===goal.c))continue;if(Math.random()<CFG[difficulty].density)w.add(`${r},${c}`);}if(bfs(w,size,START,goal))return w;}const f=new Set();for(let r=1;r<size-1;r+=1)for(let c=1;c<size-1;c+=1)if((r+c)%4===0)f.add(`${r},${c}`);return f;};
const load=()=>{setBestScore(getStringStorage('gridRunnerBestScore','-'));setBestSteps(getNumberStorage('gridRunnerBestSteps',null));setBestTime(getNumberStorage('gridRunnerBestTime',null));};useEffect(()=>load(),[]);
const reset=(newMap=false)=>{clearTimer();setState('idle');setPlayer(START);setSteps(0);setTime(0);setTrail(new Set(['0,0']));if(newMap)setWalls(gen());};
useEffect(()=>{setWalls(gen());reset(false);},[difficulty]);
const start=()=>{if(!walls.size)setWalls(gen());setState('playing');clearTimer();timerRef.current=setInterval(()=>setTime((v)=>v+1),1000);};
const saveBest=(s,t)=>{const better=bestSteps===null||s<bestSteps||(s===bestSteps&&t<bestTime);if(better){setNumberStorage('gridRunnerBestSteps',s);setNumberStorage('gridRunnerBestTime',t);const txt=`${s} steps / ${t}s`;setStringStorage('gridRunnerBestScore',txt);setBestSteps(s);setBestTime(t);setBestScore(txt);playWinSound();}};
const move=(d)=>{if(state==='completed')return;if(state==='idle')start();const [dr,dc]=DIR[d];setPlayer((cur)=>{const nr=cur.r+dr,nc=cur.c+dc,k=`${nr},${nc}`;if(nr<0||nc<0||nr>=size||nc>=size||walls.has(k))return cur;playMoveSound();setSteps((v)=>v+1);setTrail((old)=>new Set(old).add(k));if(nr===goal.r&&nc===goal.c){clearTimer();setState('completed');saveBest(steps+1,time);}return {r:nr,c:nc};});};
useEffect(()=>{if(state!=='playing')return;const onKey=(e)=>{const map={ArrowUp:'up',ArrowDown:'down',ArrowLeft:'left',ArrowRight:'right',w:'up',a:'left',s:'down',d:'right',W:'up',A:'left',S:'down',D:'right'};if(map[e.key]){if(e.key.startsWith('Arrow'))e.preventDefault();move(map[e.key]);}};window.addEventListener('keydown',onKey);return ()=>window.removeEventListener('keydown',onKey);},[state,walls,steps,time]);
return <div className='space-y-4'><div className='grid grid-cols-2 md:grid-cols-4 gap-3'>{[['ก้าว',steps],['เวลา',`${time}s`],['Best',bestScore],['Best Time',bestTime!==null?`${bestTime}s`:'-']].map(([k,v])=><div key={k} className='surface-card p-3'><p className='font-hud text-xs text-zinc-400'>{k}</p><p className='font-hud text-xl font-bold'>{v}</p></div>)}</div><div className='surface-card p-4 space-y-3'><div className='flex flex-wrap gap-2'>{Object.keys(CFG).map((k)=><button key={k} onClick={()=>setDifficulty(k)} className={`px-3 py-2 rounded-lg border font-hud text-xs ${difficulty===k?'bg-white text-black border-white':'border-white/20'}`}>{k}</button>)}<button onClick={start} className='px-4 py-2 rounded-lg bg-white text-black font-hud text-xs font-bold'>เริ่ม</button><button onClick={()=>reset(false)} className='px-4 py-2 rounded-lg border border-white/20 font-hud text-xs'>รีสตาร์ต</button><button onClick={()=>reset(true)} className='px-4 py-2 rounded-lg border border-white/20 font-hud text-xs'>แผนที่ใหม่</button></div><div className={`grid gap-1 max-w-[640px] mx-auto w-full ${state==='completed'?'win-pulse':''}`} style={{gridTemplateColumns:`repeat(${size}, minmax(0, 1fr))`}}>{Array.from({length:size*size},(_,i)=>{const r=Math.floor(i/size),c=i%size,key=`${r},${c}`;const isP=player.r===r&&player.c===c,isG=goal.r===r&&goal.c===c,isW=walls.has(key),isT=trail.has(key);return <div key={key} className={`aspect-square rounded-md border ${isW?'bg-black/20 dark:bg-zinc-800 border-black/20 dark:border-zinc-700':'border-black/10 dark:border-white/10 bg-black/[0.035] dark:bg-white/[0.035]'} ${isT&&!isW?'bg-white/[0.06]':''} grid place-items-center`}>{isP?<span className='h-3 w-3 md:h-4 md:w-4 rotate-45 bg-white shadow-[0_0_10px_rgba(255,255,255,.4)]'/>:isG?<span className='h-4 w-4 md:h-5 md:w-5 rounded-sm border border-white/80 shadow-[0_0_10px_rgba(255,255,255,.35)]'/>:null}</div>;})}</div><div className='grid grid-cols-3 gap-2 max-w-56 mx-auto pt-2'><div/><button onClick={()=>move('up')} className='surface-card py-3 font-hud'>↑</button><div/><button onClick={()=>move('left')} className='surface-card py-3 font-hud'>←</button><button onClick={()=>move('down')} className='surface-card py-3 font-hud'>↓</button><button onClick={()=>move('right')} className='surface-card py-3 font-hud'>→</button></div></div></div>;}
