'use client';
import { useEffect, useState } from 'react';
import { getStorage, setStorage } from '@/lib/storage';
const wins=[[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]];
const winner=(b,p)=>wins.find(c=>c.every(i=>b[i]===p));
const move=(b,d)=>{const open=b.map((v,i)=>v?null:i).filter(v=>v!==null); const rnd=()=>open[Math.floor(Math.random()*open.length)]; if(d==='Easy') return rnd(); const win=open.find(i=>{const n=[...b];n[i]='O';return winner(n,'O')}); const blk=open.find(i=>{const n=[...b];n[i]='X';return winner(n,'X')}); if(d==='Normal') return win??blk??rnd(); const mm=(bb,max)=>{const wX=winner(bb,'X'),wO=winner(bb,'O'); const op=bb.map((v,i)=>v?null:i).filter(v=>v!==null); if(wO) return {s:1}; if(wX) return {s:-1}; if(!op.length) return {s:0}; let best={s:max?-9:9,m:op[0]}; for(const i of op){const n=[...bb];n[i]=max?'O':'X';const s=mm(n,!max).s; if(max?s>best.s:s<best.s) best={s,m:i};} return best;}; return mm(b,true).m;};
export default function XOGame(){const [b,setB]=useState(Array(9).fill(null)); const [d,setD]=useState('Normal'); const [wc,setWc]=useState([]); const [lock,setLock]=useState(false); const w=winner(b,'X')||winner(b,'O'); const draw=!w&&b.every(Boolean);
useEffect(()=>{if(!w||w[0]!==undefined&&b[w[0]]!=='X') return; const best=getStorage('xoBestScore',0)+1; setStorage('xoBestScore',best);},[w,b]);
const play=(i)=>{if(b[i]||w||draw||lock)return; const n=[...b];n[i]='X'; const xw=winner(n,'X'); if(xw){setWc(xw);return setB(n);} if(n.every(Boolean)) return setB(n); setB(n); setLock(true); setTimeout(()=>{const m=move(n,d); if(m!==undefined&&m!==null){n[m]='O'; const ow=winner(n,'O'); if(ow) setWc(ow);} setB([...n]); setLock(false);},350);};
return <div><div className='mb-3'>Difficulty: <select value={d} onChange={e=>setD(e.target.value)}><option>Easy</option><option>Normal</option><option>Hard</option></select></div><div className='grid grid-cols-3 gap-2 max-w-xs'>{b.map((v,i)=><button key={i} onClick={()=>play(i)} className={`h-16 text-2xl border rounded ${wc.includes(i)?'bg-emerald-500/40':''}`}>{v}</button>)}</div><button className='mt-3 px-3 py-2 border rounded' onClick={()=>{setB(Array(9).fill(null));setWc([])}}>Reset</button></div>}
